server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://your server info
    username: your username
    password: your passwprd
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:**/mappers/*.xml
  type-aliases-package: com.example.demo.model
  #type-handlers-package: not defined
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
