server:
  port: 8080

spring:
  datasource:
    #url: jdbc:mysql://rgate.synology.me:33306/serviceorchestration?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://166.104.112.37:33306/so?useUnicode=true&characterEncoding=utf-8
    username: orchestrator
    password: pine123
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:**/mappers/*.xml
  type-aliases-package: com.example.demo.model
  #type-handlers-package: not defined
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
